name: AetherApp
options:
  bundleIdPrefix: com.cluvex.aether
  createIntermediateGroups: true
targets:
  AetherApp:
    type: application
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: AetherApp/Sources
      - path: AetherApp/Resources
        buildPhase: resources
        includes:
          - "*.swift"
          - "*.plist"
          - "*.mac"
          - "Assets.xcassets"
    info:
      path: AetherApp/Resources/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.cluvex.aether
        CODE_SIGN_ENTITLEMENTS: AetherApp/Resources/entitlements.mac
        ENABLE_HARDENED_RUNTIME: true
        INFOPLIST_FILE: AetherApp/Resources/Info.plist
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        COMBINE_HIDPI_IMAGES: true
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        RUN_DOCUMENTATION_COMPILER: false
